/*Copyright (c) 2015-2016 wavemaker-com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker-com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker-com*/
package com.wavemakersample.compose.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.wavemaker.runtime.data.dao.WMGenericDao;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.file.model.Downloadable;

import com.wavemakersample.compose.Todos;


/**
 * ServiceImpl object for domain model class Todos.
 *
 * @see Todos
 */
@Service("compose.TodosService")
public class TodosServiceImpl implements TodosService {

    private static final Logger LOGGER = LoggerFactory.getLogger(TodosServiceImpl.class);


    @Autowired
    @Qualifier("compose.TodosDao")
    private WMGenericDao<Todos, Integer> wmGenericDao;

    public void setWMGenericDao(WMGenericDao<Todos, Integer> wmGenericDao) {
        this.wmGenericDao = wmGenericDao;
    }

    @Transactional(value = "composeTransactionManager")
    @Override
	public Todos create(Todos todos) {
        LOGGER.debug("Creating a new Todos with information: {}", todos);
        Todos todosCreated = this.wmGenericDao.create(todos);
        return todosCreated;
    }

	@Transactional(readOnly = true, value = "composeTransactionManager")
	@Override
	public Todos getById(Integer todosId) throws EntityNotFoundException {
        LOGGER.debug("Finding Todos by id: {}", todosId);
        Todos todos = this.wmGenericDao.findById(todosId);
        if (todos == null){
            LOGGER.debug("No Todos found with id: {}", todosId);
            throw new EntityNotFoundException(String.valueOf(todosId));
        }
        return todos;
    }

    @Transactional(readOnly = true, value = "composeTransactionManager")
	@Override
	public Todos findById(Integer todosId) {
        LOGGER.debug("Finding Todos by id: {}", todosId);
        return this.wmGenericDao.findById(todosId);
    }


	@Transactional(rollbackFor = EntityNotFoundException.class, value = "composeTransactionManager")
	@Override
	public Todos update(Todos todos) throws EntityNotFoundException {
        LOGGER.debug("Updating Todos with information: {}", todos);
        this.wmGenericDao.update(todos);

        Integer todosId = todos.getId();

        return this.wmGenericDao.findById(todosId);
    }

    @Transactional(value = "composeTransactionManager")
	@Override
	public Todos delete(Integer todosId) throws EntityNotFoundException {
        LOGGER.debug("Deleting Todos with id: {}", todosId);
        Todos deleted = this.wmGenericDao.findById(todosId);
        if (deleted == null) {
            LOGGER.debug("No Todos found with id: {}", todosId);
            throw new EntityNotFoundException(String.valueOf(todosId));
        }
        this.wmGenericDao.delete(deleted);
        return deleted;
    }

	@Transactional(readOnly = true, value = "composeTransactionManager")
	@Override
	public Page<Todos> findAll(QueryFilter[] queryFilters, Pageable pageable) {
        LOGGER.debug("Finding all Todos");
        return this.wmGenericDao.search(queryFilters, pageable);
    }

    @Transactional(readOnly = true, value = "composeTransactionManager")
    @Override
    public Page<Todos> findAll(String query, Pageable pageable) {
        LOGGER.debug("Finding all Todos");
        return this.wmGenericDao.searchByQuery(query, pageable);
    }

    @Transactional(readOnly = true, value = "composeTransactionManager")
    @Override
    public Downloadable export(ExportType exportType, String query, Pageable pageable) {
        LOGGER.debug("exporting data in the service compose for table Todos to {} format", exportType);
        return this.wmGenericDao.export(exportType, query, pageable);
    }

	@Transactional(readOnly = true, value = "composeTransactionManager")
	@Override
	public long count(String query) {
        return this.wmGenericDao.count(query);
    }



}

